### PR TITLE
Add CLI command.

### PR DESCRIPTION
**Pull request by jwalton**
Lets you run this from the command line.

### CODE REVIEW

**Comment by marcellodesales** [comment]
Hi @jwalton 
Thanks a lot for providing this pull request... It works perfectly if I use the "command.js" directly, but not out-of-the-box as described in the README.md section you created... Could you please provide instructions on the restrictions on it so I can merge this pull request? :dart: 

For instance, I have a cob.xml and the output dir as you specified... 

```
mdesales@ubuntu [05/30/201513:28:31] /tmp/istanbul-cobertura-badger (master) $ ls -la cob.xml 
-rw-rw-r-- 1 mdesales mdesales 4237 May 30 13:21 cob.xml
mdesales@ubuntu [05/30/201513:32:48] /tmp/istanbul-cobertura-badger (master) $ file out/
out/: directory
```

Now, I'm not sure why, but the command did not get to my $PATH, nor in the `node_modules/.bin` directory...

```
mdesales@ubuntu [05/30/201513:35:38] /tmp/istanbul-cobertura-badger (master) $ tree node_modules/.bin/
node_modules/.bin/
├── gulp -> ../gulp/bin/gulp.js
├── jshint -> ../jshint/bin/jshint
├── mocha -> ../mocha/bin/mocha
├── _mocha -> ../mocha/bin/_mocha
└── rimraf -> ../rimraf/bin.js

0 directories, 5 files
```

Is there anything specific that we need to document to make it work? I'm on Node v0.10.33.

```
mdesales@ubuntu [05/30/201513:32:26] /tmp/istanbul-cobertura-badger (master) $ istanbul-cobertura-badger cob.xml out/
istanbul-cobertura-badger: command not found
```

Thanks!
Marcello

**Comment by jwalton** [comment]
Tryin cloning a copy of my changes, and do `npm link .` in the folder, then cd to some other project and run `npm link istanbul-cobertura-badger`.  This is going to simulate doing an "npm install" with these changes.  You should find a ./node_modules/.bin/istanbul-cobertura-badger in the other project after you do this.  This happens because of the `bin` section in package.json.

**Comment by marcellodesales** [comment]
@jwalton Perfect! It works!

Just as a matter of making this feature work properly, can you provide a validation for the command, showing the proper inputs like in a command help?

```
mdesales@ubuntu [06/05/201512:50:40] ~/dev/github/jwalton/istanbul-cobertura-badger (master) $ istanbul-cobertura-badger 

fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory './coverage/cobertura-coverage.xml'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at gulpIstanbulBadger (/home/mdesales/dev/github/jwalton/istanbul-cobertura-badger/index.js:27:31)
    at Object.<anonymous> (/home/mdesales/dev/github/jwalton/istanbul-cobertura-badger/command.js:18:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Other than that, I can merge this change!

thanks!

**Comment by marcellodesales** [comment]
@jwalton Thanks a lot for contributing!

**Pull request merged**
